### ISSUE TITLE
Neue API Funktionen

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv8-PTR#1]
Hallo,
Nachdem ich die folgenden Änderungen gemacht habe, läuft die UI bei mir auf dem PTR Ohne Fehler:
1.) func_UF.lua
Zeile 477 / 478 alt:
	local mana = UnitMana("player")
	local maxmana = UnitManaMax("player")
Zeile 477 / 478 neu:
	local mana = UnitPower("player")
	local maxmana = UnitPowerMax("player")
Da voher ja schon abgefragt wird 
	if self.parent.unit ~= "player" or UpdateManaLevelDelay < .2 or UnitIsDeadOrGhost("player") or UnitPowerType("player") ~= 0 then return end
wird die Optionale Variable für den PowerType nicht benötigt.

2.) artifactpower.lua
Zeile 34 / 64 alt:
local _, _, _, _, totalxp, pointsSpent, _, _, _, _, _, _ = C_ArtifactUI.GetEquippedArtifactInfo()

Zeile 34 / 64 neu:
local _, _, _, _, totalxp, pointsSpent, _, _, _, _, _, _, artifactTier  = C_ArtifactUI.GetEquippedArtifactInfo()

Zeile 35 alt:
local _, xp, xpForNextPoint = MainMenuBar_GetNumArtifactTraitsPurchasableFromXP(pointsSpent, totalxp)

Zeile 35 neu:
local _, xp, xpForNextPoint = MainMenuBar_GetNumArtifactTraitsPurchasableFromXP(pointsSpent, totalxp, artifactTier)

Zeile 65 alt:
local numPointsAvailableToSpend, xp, xpForNextPoint = MainMenuBar_GetNumArtifactTraitsPurchasableFromXP(pointsSpent, totalxp)

Zeile 65 neu:
local numPointsAvailableToSpend, xp, xpForNextPoint = MainMenuBar_GetNumArtifactTraitsPurchasableFromXP(pointsSpent, totalxp, artifactTier)

Gruß Ralf

**Comment by liquidbase** [comment]
Mit dem Commit heute hinzugefügt
