### ISSUE TITLE
Probleme mit dem neuen Build für PTR

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv8-PTR#2]
Hallo,
Ich habe das heute mal getestet mit dem Build von gestern. Beim DH habe ich keine Probleme, aber beim Druiden. Dort habe ich keine Unit Frames mehr, bzw. die Unit Frames Target werden im Standard Blizzard angezeigt. Desweiteren ist der Player Cast bar immer sichtbar weiß und wenn man castet bleibt er so, statt dessen erscheint der Blizzard eigene Player castbar. Ich habe dann noch einmal den alten Build eingespielt, dann die Dateien func_UF.lua und artifactpower.lua aus dem neuen Build ersetzt. Dann läuft Alles ohne Probleme. Diesen Fehler bekomme ich beim Druiden beim Einloggen:

1x DuffedUI\libs\plugins\oUF_ComboPointsBar.lua:116: attempt to index local 'Point' (a nil value)
DuffedUI\libs\plugins\oUF_ComboPointsBar.lua:116: in function `enable'
DuffedUI\libs\oUF\ouf.lua:99: in function `EnableElement'
DuffedUI\libs\oUF\ouf.lua:269: in function <DuffedUI\libs\oUF\ouf.lua:192>
(tail call): ?
DuffedUI\libs\oUF\ouf.lua:555: in function `Spawn'
...eDuffedUI\modules\unitframes\constructor.lua:44: in function `SpawnUF'
...eDuffedUI\modules\unitframes\constructor.lua:330: in function `LoadUF'
...eDuffedUI\modules\unitframes\constructor.lua:338: in function `?'
...eDuffedUI\modules\unitframes\constructor.lua:336: in function <...eDuffedUI\modules\unitframes\constructor.lua:336>

Locals:
self = oUF_Player {
 0 = <userdata>
 UNIT_PORTRAIT_UPDATE = <function> defined @DuffedUI\libs\oUF\elements\portraits.lua:75
 Combat = <unnamed> {
 }
 __tags = <table> {

**Comment by Potsrabe** [comment]
Hallo,
Habe das heute noch einmal getestet. Das Problem liegt in der Bibliotheksdatei oUF_ComboPointsBar.lua . Die alte Datei läuft ohne Probleme. Wenn ich in der neuen Datei Zeile 114 von for i = 1, 10 do  auf
for i = 1, 8 do ändere sind die Unitframes und der Castbar wieder o.k., aber auf dem Unitframe ist permanent das Gruppenleiter Symbol angezeigt und über dem Bar in der Mitte 6 kleine bunte Punkte. Ändere ich Zeile 76 ebenfalls von for i = 1, 10 do auf for i = 1, 8 do ist wieder Alles normal. Allerdings erhalte ich in allen Gestalten außer Heilung die Warnung "Wenig Mana".

**Comment by Potsrabe** [comment]
Hallo, Ich habe noch eine andere Idee, die ich heute Abend mal testen werde. Die läuft darauf hinaus, Zeile 38 und Zeile 48 von for i = 1, 8 do auf for i = 1, 10 do zu ändern. Damit würde cbp immer bis 10 hoch laufen (vorher auf 8) egal, ob MaxCombo 10, 6 oder 5 ist.

**Comment by liquidbase** [comment]
Hab das ganze nochmal angepasst. Original-Datei genutzt aber mit dem Zusatz das die Combopoints jetzt auf 10 gehen.
Da ich das nicht vernünftig testen kann, wäre es toll wenn du das machen kannst. Kann keinen Druiden oder Schurken transferieren und soweit leveln das es relevant wird schaffe ich zeitlich nicht.

**Comment by Potsrabe** [comment]
Hallo,
Schurke konnte ich nicht testen. Beim Druiden gibt es aber immer noch den Fehler mit NIL Value. Diesmal in Zeile 107.

**Comment by Potsrabe** [comment]
Hallo,
Ich habe die Lib einfach mal mit meinem Schurken auf dem Live Server getestet. Gleiche Fehler wie beim Druiden. Im Originalzustand kommt der Fehler in Zeile 107, solange bis man 106 von 10 auf 8 verringert. Wenn man das gemacht hat, Kommt der Fehler in Zeile 60 und 66, egal welche Talent Skillung man hat (Deeper, Anticapation oder Vigor). Sprich die Abfrage:
    if (Anticipation and class == "ROGUE") then
wird scheinbar komplett ignoriert und funktioniert selbst bei Anticipation nicht mit 10 sondern auch nur mit 8 (Zeile 61). 
Zeile 34 verursacht den gleichen Effekt wie beim Druiden. bei Schleife bis 8 ist alles O.K. bei Schleife bis 10 werden falsche Symbole am Unitframe angezeigt (Gruppenführer, im Kampf und so kleine bunte Punkte über dem Frame.

Gruß Ralf

**Comment by liquidbase** [comment]
Hab gerade nochmal ein Commit gemacht. Teste es bitte mal dem Build.
Schätze mal das der Fehler daran lag das in der Lib von 10 die Rede ist aber die Anzeigeelemente beim Druid und Schurken nur von 8 wussten.

**Comment by Potsrabe** [comment]
Hallo,
Passt fast. Jetzt muss noch die Color Tabelle in der oUF_ComboPointsBar.lua om zwei Werte erweitert werden:
    [9] = {.33, .63, .33, 1},
    [10] = {.33, .63, .33, 1},	

Dann sind alle Fehler weg.

**Comment by liquidbase** [comment]
Das ist ein einfaches. Commit kommt dann sofort und danke fürs testen :)

**Comment by Potsrabe** [comment]
Bitte, immer wieder gerne.

**Comment by Potsrabe** [comment]
Hallo, ich habe das eben noch mal auf dem Live Server mit dem Schurken getestet. Pass auch hier einwandfrei. Je nach Talent werden 10 , 6 oder 5 Combopunkte angezeigt.

Dann schönen Wochenende
